// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybgzameatlcbejngsfmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliZ3phbWVhdGxjYmVqbmdzZm1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjMxMDcsImV4cCI6MjA3MDMzOTEwN30.OjhdjvedF5246OH7MJgosBh2bOeACnIIFeltqCMQuIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});